# -*- coding: utf-8 -*-
"""Jira Integration Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vykBrsFixtw9MSv5sC6vE5wbqkvmw85b
"""

import requests
import json
import sys
import os

# Configuration - Use environment variables for security
JIRA_URL = "https://cmext.ahrq.gov/jira"
# Replace with your token or set as environment variable
JIRA_TOKEN = os.getenv("JIRA_TOKEN", "YOUR_PAT_HERE")

def create_jira_issue(project_key, summary, description, issue_type="Task"):
    """Creates a new Jira issue."""
    url = f"{JIRA_URL}/rest/api/2/issue"

    headers = {
        "Authorization": f"Bearer {JIRA_TOKEN}",
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    payload = {
        "fields": {
            "project": {"key": project_key},
            "summary": summary,
            "description": description,
            "issuetype": {"name": issue_type}
        }
    }

    response = requests.post(url, headers=headers, data=json.dumps(payload))

    if response.status_code == 201:
        print(f"Successfully created issue: {response.json()['key']}")
        return response.json()['key']
    else:
        print(f"Failed to create issue. Status code: {response.status_code}")
        print(response.text)
        return None

def add_comment(issue_key, comment_body):
    """Adds a comment to an existing Jira issue."""
    url = f"{JIRA_URL}/rest/api/2/issue/{issue_key}/comment"

    headers = {
        "Authorization": f"Bearer {JIRA_TOKEN}",
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    payload = {"body": comment_body}

    response = requests.post(url, headers=headers, data=json.dumps(payload))

    if response.status_code == 201:
        print(f"Successfully added comment to {issue_key}")
    else:
        print(f"Failed to add comment. Status code: {response.status_code}")
        print(response.text)

def get_issue_details(issue_key):
    """Retrieves details of a Jira issue."""
    url = f"{JIRA_URL}/rest/api/2/issue/{issue_key}"

    headers = {
        "Authorization": f"Bearer {JIRA_TOKEN}",
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        issue_data = response.json()
        return {
            "key": issue_data.get("key"),
            "summary": issue_data.get("fields", {}).get("summary"),
            "description": issue_data.get("fields", {}).get("description"),
            "status": issue_data.get("fields", {}).get("status", {}).get("name"),
            "assignee": issue_data.get("fields", {}).get("assignee", {}).get("displayName"),
            "created": issue_data.get("fields", {}).get("created"),
            "updated": issue_data.get("fields", {}).get("updated"),
            "issue_type": issue_data.get("fields", {}).get("issuetype", {}).get("name"),
            "priority": issue_data.get("fields", {}).get("priority", {}).get("name")
        }
    else:
        print(f"Failed to get issue details. Status code: {response.status_code}")
        print(response.text)
        return None

def change_issue_status(issue_key, transition_name):
    """Changes the status of a Jira issue by transitioning it."""
    # First, get available transitions
    url = f"{JIRA_URL}/rest/api/2/issue/{issue_key}/transitions"
    
    headers = {
        "Authorization": f"Bearer {JIRA_TOKEN}",
        "Content-Type": "application/json",
        "Accept": "application/json"
    }
    
    response = requests.get(url, headers=headers)
    
    if response.status_code != 200:
        print(f"Failed to get transitions. Status code: {response.status_code}")
        print(response.text)
        return False
    
    transitions = response.json().get("transitions", [])
    
    # Find the transition ID matching the transition name
    transition_id = None
    for transition in transitions:
        if transition.get("name").lower() == transition_name.lower():
            transition_id = transition.get("id")
            break
    
    if not transition_id:
        print(f"Transition '{transition_name}' not found. Available transitions:")
        for transition in transitions:
            print(f"  - {transition.get('name')}")
        return False
    
    # Perform the transition
    url = f"{JIRA_URL}/rest/api/2/issue/{issue_key}/transitions"
    payload = {
        "transition": {
            "id": transition_id
        }
    }
    
    response = requests.post(url, headers=headers, data=json.dumps(payload))
    
    if response.status_code == 204:
        print(f"Successfully transitioned {issue_key} to '{transition_name}'")
        return True
    else:
        print(f"Failed to transition issue. Status code: {response.status_code}")
        print(response.text)
        return False

if __name__ == "__main__":
    # Example usage for testing
    # create_jira_issue("AQD", "Test Ticket from Script", "Created via Python API")
    pass