name: Jira Sync
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize]

jobs:
  sync-to-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare action directory
        run: cp jira_integration_script.py .github/actions/jira-sync/

      - name: Run Jira Sync Action
        uses: ./.github/actions/jira-sync
        with:
          jira-url: 'https://cmext.ahrq.gov/jira'
          jira-token: ${{ secrets.JIRA_TOKEN }}
          project-key: 'CLOUD'
          event-name: ${{ github.event_name }}
          issue-title: ${{ github.event.issue.title }}
          issue-url: ${{ github.event.issue.html_url }}
          pr-branch: ${{ github.head_ref }}
          pr-url: ${{ github.event.pull_request.html_url }}
